language: node_js
sudo: false
node_js:
  - 10
addons:
  chrome: stable
env:
  global: CODECOV_TOKEN=$CODECOV_TOKEN
install:
  - npm install
# script:
#   - ng test --code-coverage --watch false --browsers=ChromeHeadless
jobs:
  include:
    - stage: Test coverage
      script:
        - ng test --browsers=ChromeHeadlessNoSandbox --codeCoverage=true --watch=false
      after_script:
        - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./node_modules/.bin/codecov; fi
